export const PayrollRegisterData = [
  {
    year: 2024,
    months: [
      {
        month: 1,
        status: "Created",
        createdAt: "01-2-2024",
        PayrollName: "Monthly Payroll - January 2024",
        updatedAt: "01-2-2024",
        ProcessedAt: "01-2-2024",
        EmployeeAttandanceData: [
          {
            isAttChecked: true,
            firstName: "Abhay",
            lastName: "Abhay",
            empId: "KAS001",
            profile: "",
            status: "Active",
            shift: "Morning",
            daysInMonth: 31,
            absent: 15,
            present: 13,
            holiday: 1,
            halfday: 2,
            NCNS: 0,
            Sandwhich: 0,
            paidLeaves: 1,
            unpaidLeaves: 0,
            totalPayableDays: 15,
            fixedBasic: 60000,
            fixedHRA: 30000,
            fixedConvenyance: 1600,
            fixedOthers: 58400,
            fixedTotalSalary: 150000,
            actualBasic: 29032,
            actualHRA: 14516,
            actualConvenyance: 774,
            actualOthers: 28258,
            actualTotalSalary: 72581,
            bonusAmount: 6000,
            bonusType: "Performance",
            insentiveAmount: 20000,
            insentiveType: "Target Achieved",
            totalBNIAdditions: 26000,
            additionComment: "Some reason for bonus or incentive amount",
            salaryaAfterBonusAndInsentive: 98581,
            ArrearMonth: "25-12-2024",
            ArrearAmountPay: 1000,
            ArrearAmountDeduct: 0,
            SalaryAfterArrearAmt: 99081,
            arrearMessage: "Some reason for arrear amount",
            PFDeduction: 1800,
            ESIDedeuction: 0,
            TDSDeduction: 3000,
            totalDeductionsAmount: 4800,
            deductionNotes: "Some reason for deductions amount",
            salaryAfterPFESIandTDS: 94281,
            reimbursmentApplied: 10000,
            reimbursmentApproved: 5000,
            salaryAfterReimbursment: 99281,
            advanceDuration: "6 months",
            PreviousAdvance: 5000,
            advanceAmountPay: "",
            advanceAmountDeduct: 3000,
            advanceBalance: 2000,
            netSalaryPayable: 96281,
            ReasionForAdvance: "Some reason for advance salary amount",
          },
          {
            isAttChecked: true,
            firstName: "Priya",
            lastName: "Sharma",
            empId: "KAS002",
            profile: "",
            status: "Active",
            shift: "Evening",
            daysInMonth: 31,
            absent: 10,
            present: 20,
            holiday: 1,
            halfday: 0,
            NCNS: 0,
            Sandwhich: 0,
            paidLeaves: 0,
            unpaidLeaves: 0,
            totalPayableDays: 21,
            fixedBasic: 55000,
            fixedHRA: 25000,
            fixedConvenyance: 2000,
            fixedOthers: 50000,
            fixedTotalSalary: 132000,
            actualBasic: 37096,
            actualHRA: 16888,
            actualConvenyance: 1354,
            actualOthers: 35562,
            actualTotalSalary: 90800,
            bonusAmount: 8000,
            bonusType: "Performance",
            insentiveAmount: 10000,
            insentiveType: "Extra Project",
            totalBNIAdditions: 18000,
            additionComment: "Excellent project delivery",
            salaryaAfterBonusAndInsentive: 108800,
            ArrearMonth: "20-12-2024",
            ArrearAmountPay: 1000,
            ArrearAmountDeduct: 0,
            SalaryAfterArrearAmt: 109800,
            arrearMessage: "Appraisal pending",
            PFDeduction: 2000,
            ESIDedeuction: 0,
            TDSDeduction: 2500,
            totalDeductionsAmount: 4500,
            deductionNotes: "Regular deductions",
            salaryAfterPFESIandTDS: 105300,
            reimbursmentApplied: 8000,
            reimbursmentApproved: 4000,
            salaryAfterReimbursment: 109300,
            advanceDuration: "3 months",
            PreviousAdvance: 3000,
            advanceAmountPay: "",
            advanceAmountDeduct: 1500,
            advanceBalance: 1500,
            netSalaryPayable: 107800,
            ReasionForAdvance: "Family emergency",
          },
        ],
      },
    ],
  },
  {
    year: 2025,
    months: [
      {
        month: 1,
        status: "Created",
        createdAt: "01-02-2025",
        PayrollName: "Monthly Payroll - January 2025",
        updatedAt: "01-02-2025",
        ProcessedAt: "01-02-2025",
        EmployeeAttandanceData: [
          {
            isAttChecked: true,
            firstName: "Abhay",
            lastName: "Abhay",
            empId: "KAS001",
            profile: "",
            status: "Active",
            shift: "Morning",
            daysInMonth: 31,
            absent: 15,
            present: 13,
            holiday: 1,
            halfday: 2,
            NCNS: 0,
            Sandwhich: 0,
            paidLeaves: 1,
            unpaidLeaves: 0,
            totalPayableDays: 15,
            fixedBasic: 60000,
            fixedHRA: 30000,
            fixedConvenyance: 1600,
            fixedOthers: 58400,
            fixedTotalSalary: 150000,
            actualBasic: 29032,
            actualHRA: 14516,
            actualConvenyance: 774,
            actualOthers: 28258,
            actualTotalSalary: 72581,
            bonusAmount: 6000,
            bonusType: "Performance",
            insentiveAmount: 20000,
            insentiveType: "Target Achieved",
            totalBNIAdditions: 26000,
            additionComment: "Some reason for bonus or incentive amount",
            salaryaAfterBonusAndInsentive: 98581,
            ArrearMonth: "25-12-2024",
            ArrearAmountPay: 1000,
            ArrearAmountDeduct: 0,
            SalaryAfterArrearAmt: 99081,
            arrearMessage: "Some reason for arrear amount",
            PFDeduction: 1800,
            ESIDedeuction: 0,
            TDSDeduction: 3000,
            totalDeductionsAmount: 4800,
            deductionNotes: "Some reason for deductions amount",
            salaryAfterPFESIandTDS: 94281,
            reimbursmentApplied: 10000,
            reimbursmentApproved: 5000,
            salaryAfterReimbursment: 99281,
            advanceDuration: "6 months",
            PreviousAdvance: 5000,
            advanceAmountPay: "",
            advanceAmountDeduct: 3000,
            advanceBalance: 2000,
            netSalaryPayable: 96281,
            ReasionForAdvance: "Some reason for advance salary amount",
          },
          {
            isAttChecked: true,
            firstName: "Priya",
            lastName: "Sharma",
            empId: "KAS002",
            profile: "",
            status: "Active",
            shift: "Evening",
            daysInMonth: 31,
            absent: 10,
            present: 20,
            holiday: 1,
            halfday: 0,
            NCNS: 0,
            Sandwhich: 0,
            paidLeaves: 0,
            unpaidLeaves: 0,
            totalPayableDays: 21,
            fixedBasic: 55000,
            fixedHRA: 25000,
            fixedConvenyance: 2000,
            fixedOthers: 50000,
            fixedTotalSalary: 132000,
            actualBasic: 37096,
            actualHRA: 16888,
            actualConvenyance: 1354,
            actualOthers: 35562,
            actualTotalSalary: 90800,
            bonusAmount: 8000,
            bonusType: "Performance",
            insentiveAmount: 10000,
            insentiveType: "Extra Project",
            totalBNIAdditions: 18000,
            additionComment: "Excellent project delivery",
            salaryaAfterBonusAndInsentive: 108800,
            ArrearMonth: "20-12-2024",
            ArrearAmountPay: 1000,
            ArrearAmountDeduct: 0,
            SalaryAfterArrearAmt: 109800,
            arrearMessage: "Appraisal pending",
            PFDeduction: 2000,
            ESIDedeuction: 0,
            TDSDeduction: 2500,
            totalDeductionsAmount: 4500,
            deductionNotes: "Regular deductions",
            salaryAfterPFESIandTDS: 105300,
            reimbursmentApplied: 8000,
            reimbursmentApproved: 4000,
            salaryAfterReimbursment: 109300,
            advanceDuration: "3 months",
            PreviousAdvance: 3000,
            advanceAmountPay: "",
            advanceAmountDeduct: 1500,
            advanceBalance: 1500,
            netSalaryPayable: 107800,
            ReasionForAdvance: "Family emergency",
          },
        ],
      },
    ],
  },
];
